export const testData = [
  {
    sdlId: "yxcvyxvadfa",
    type: "airfreight",
    wayBills: [
      {
        id: "skodk",
        packages: [
          {
            id: "abda1234",
            packageNumber: "asd1",
            itemCount: 2,
            weight: 24,
            packaging: "folie",
            goodType: "krmivo",
            stackable: true,
            status: "",
            reasonOfDelay: "",
            sectionEnabled: false,
          },
        ],
        shipmentConfirm: {
          contacted: true,
          capacityBooked: true,
          documents: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
          confirmationDate: "2022-11-01T20:12:39+01:00",
          clientReference: "X4092349TET",
          reasonOfDelay: "",
          sectionEnabled: true,
        },
        pickedUp: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          exportCustoms: true,
          goodsTendered: true,
          status: "delayed",
          reasonOfDelay: "Porucha na vozidle",
          sectionEnabled: false,
        },
        flightDeparture: {
          flights: [
            {
              actualTime: "2022-11-01T20:12:39+01:00",
              estimatedTime: "2022-11-01T20:12:39+01:00",
              airport: "AAEV",
              flightNumber: "AA66677",
              status: "delayed",
              reasonOfDelay: "",
              sectionEnabled: false,
            },
          ],
        },
        flightArrival: {
          airlineNotification: true,
          importCustoms: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "done",
          reasonOfDelay: "",
          sectionEnabled: false,
        },
        goodsPickedUp: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "delayed",
          reasonOfDelay: "",
          sectionEnabled: false,
        },
        goodsDelivered: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "late",
          reasonOfDelay: "Car issues",
          pod: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          sectionEnabled: false,
        },
      },
    ],
  },
  {
    sdlId: "1122334455",
    type: "airfreight",
    subscribedEmails: ["jozo@gmail.com", "peter@gmail.com"],
    wayBills: [
      {
        id: "skodk",
        packages: [
          {
            id: "abda1234",
            packageNumber: "package 1",
            itemCount: 2,
            weight: 24,
            packaging: "folie",
            goodType: "krmivo",
            stackable: true,
            status: "late",
            reasonOfDelay: "",
            sectionEnabled: true,
          },
          {
            id: "abda1223",
            packageNumber: "package 2",
            itemCount: 2,
            weight: 24,
            packaging: "folie",
            goodType: "palivo",
            stackable: true,
            status: "late",
            reasonOfDelay: "",
            sectionEnabled: true,
          },
        ],
        shipmentConfirm: {
          contacted: true,
          ticketsBooked: true,
          currierReserved: true,
          capacityBooked: true,
          vehicleETA: "2022-11-01T20:12:39+01:00",
          documents: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
          confirmationDate: "2022-11-01T20:12:39+01:00",
          clientReference: "X4092349TET",
          reasonOfDelay: "",
          sectionEnabled: true,
        },
        loadingPlace: {
          vehicleETA: "2022-11-01T20:12:39+01:00",
          vehicleArrived: true,
          status: "done",
          reasonOfDelay: "",
          sectionEnabled: true,
        },

        collected: {
          actualTime: "2022-11-01T20:12:39+01:00",
          status: "done",
          reasonOfDelay: "",
          sectionEnabled: true,
        },
        unloadingPlace: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "done",
          reasonOfDelay: "",
          sectionEnabled: true,
        },

        pickedUp: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          exportCustoms: true,
          goodsCheckedIn: true,
          goodsConfirmedOnboard: false,
          status: "done",
          reasonOfDelay: "",
          sectionEnabled: true,
        },
        flightDeparture: {
          flights: [
            {
              id: "1",
              actualTime: "2022-11-01T20:12:39+01:00",
              estimatedTime: "2022-11-01T20:12:39+01:00",
              airport: "AAEV",
              flightNumber: "AA66677",
              status: "done",
              inTransit: "true",
              sectionEnabled: true,
              reasonOfDelay: "",
            },
          ],
        },
        flightArrival: {
          airlineNotification: true,
          importCustoms: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "done",
          sectionEnabled: true,
        },
        goodsRetrieved: {
          actualTime: "2022-11-01T20:12:39+01:00",
          status: "done",
          sectionEnabled: true,
        },
        goodsHanded: {
          goodsHanded: true,
          status: "done",
          sectionEnabled: true,
        },
        goodsDelivered: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          pod: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
          sectionEnabled: true,
        },
      },
      {
        id: "fdifjdif",
        packages: [
          {
            id: "abda1239",
            packageNumber: "package 3",
            itemCount: 2,
            weight: 24,
            packaging: "folie",
            goodType: "krmivo",
            stackable: true,
            status: "late",
            sectionEnabled: true,
          },
          {
            id: "abda9223",
            packageNumber: "package 4",
            itemCount: 2,
            weight: 24,
            packaging: "folie",
            goodType: "palivo",
            stackable: true,
            status: "late",
            sectionEnabled: true,
          },
        ],
        shipmentConfirm: {
          contacted: true,
          ticketsBooked: true,
          currierReserved: true,
          capacityBooked: true,
          vehicleETA: "2022-11-01T20:12:39+01:00",
          documents: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
          confirmationDate: "2022-11-01T20:12:39+01:00",
          clientReference: "X4092349TET",
          sectionEnabled: true,
        },
        pickedUp: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          exportCustoms: true,
          goodsCheckedIn: true,
          goodsConfirmedOnboard: false,
          status: "done",
          sectionEnabled: false,
        },
        flightDeparture: {
          flights: [
            {
              actualTime: "2022-11-01T20:12:39+01:00",
              estimatedTime: "2022-11-01T20:12:39+01:00",
              airport: "AAEV",
              flightNumber: "AA66677",
              status: "done",
              sectionEnabled: false,
              reasonOfDelay: "",
            },
          ],
        },
        flightArrival: {
          airlineNotification: true,
          importCustoms: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "done",
          sectionEnabled: false,
        },
        goodsRetrieved: {
          actualTime: "2022-11-01T20:12:39+01:00",
          status: "done",
          sectionEnabled: false,
        },
        goodsHanded: {
          goodsHanded: true,
          status: "done",
          sectionEnabled: true,
        },
        goodsDelivered: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          pod: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
          sectionEnabled: true,
        },
      },
    ],
  },
  {
    sdlId: "bfdgjdhs",
    type: "drf",
    wayBills: [
      {
        id: "skodk",
        packages: [
          {
            packageId: "abda1234",
            packageNumber: "asdasdd",
            itemCount: 2,
            weight: 24,
            packaging: "folie",
            goodType: "krmivo",
            stackable: true,
            status: "late",
          },
        ],
        shipmentConfirm: {
          status: "done",
          confirmationDate: "2022-11-01T20:12:39+01:00",
          clientReference: "X4092349TET",
        },
        loadingPlace: {
          vehicleETA: "2022-11-01T20:12:39+01:00",
          vehicleArrived: true,
          status: "done",
        },
        collected: {
          actualTime: "2022-11-01T20:12:39+01:00",
          status: "done",
        },
        unloadingPlace: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "done",
        },
        goodsDelivered: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          pod: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
        },
      },
    ],
  },
  {
    sdlId: "bsngfnf",
    type: "charter",
    wayBills: [
      {
        id: "skodk",
        packages: [
          {
            packageId: "abda1234",
            packageNumber: "odk2",
            itemCount: 2,
            weight: 24,
            packaging: "folie",
            goodType: "krmivo",
            stackable: true,
            status: "late",
          },
        ],
        shipmentConfirm: {
          contacted: true,
          capacityBooked: true,
          documents: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
          confirmationDate: "2022-11-01T20:12:39+01:00",
          clientReference: "X4092349TET",
        },
        pickedUp: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          exportCustoms: true,
          status: "done",
        },
        flightDeparture: {
          flights: [
            {
              actualTime: "2022-11-01T20:12:39+01:00",
              estimatedTime: "2022-11-01T20:12:39+01:00",
              airport: "AAEV",
              flightNumber: "AA66677",
              status: "done",
              reasonOfDelay: "",
            },
          ],
        },
        flightArrival: {
          airlineNotification: true,
          importCustoms: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          status: "done",
        },
        goodsRetrieved: {
          actualTime: "2022-11-01T20:12:39+01:00",
          status: "done",
        },
        goodsHanded: {
          goodsHanded: true,
          status: "done",
        },
        goodsDelivered: {
          actualTime: "2022-11-01T20:12:39+01:00",
          estimatedTime: "2022-11-01T20:12:39+01:00",
          pod: ["https://www.jakpsatweb.cz/komix/obrazky.gif"],
          status: "done",
        },
      },
    ],
  },
];
